theme: jekyll-theme-minimal
title: sreekar's homepage
description: Bookmark this to keep an eye on my project updates!
<meta name="google-site-verification" content="ie5JFJaZb89TRxLpotUd0OkPuTBiDxeIahRas2emAOU" />
