# _config.yml

title: My Awesome Site
description: A personal site hosted on GitHub Pages

theme: jekyll-minima # or any theme you're using
plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_site_verification: ie5JFJaZb89TRxLpotUd0OkPuTBiDxeIahRas2emAOU
github_repo: https://github.com/automatorplus68-sketch/automation-of-ai

# Optional extras
markdown: kramdown
highlighter: rouge



